//
// Created by gchiappe on 2022-02-10.
//

#ifndef KETTEQ_POSTGRESQL_EXTENSIONS_COMMON_H
#define KETTEQ_POSTGRESQL_EXTENSIONS_COMMON_H

#include "common/util.h"

#endif //KETTEQ_POSTGRESQL_EXTENSIONS_COMMON_H
